

module AbsGrammok where

-- Haskell module generated by the BNF converter




data ExpT
    = Tree Integer [ExpT]
    | Leaf Integer
    | FTree Double [ExpT]
    | FLeaf Double
  deriving (Eq, Ord, Show, Read)

