module SkelGrammok where

-- Haskell module generated by the BNF converter

import AbsGrammok
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transExpT :: ExpT -> Result
transExpT x = case x of
  Tree integer expts -> failure x
  Leaf integer -> failure x
  FTree double expts -> failure x
  FLeaf double -> failure x

